/** Top ~100 US large-cap tickers — prices from Yahoo in dev. */
export type Company = { symbol: string; name: string; sector: string };

export const COMPANIES: Company[] = [
  { symbol: "AAPL", name: "Apple", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet (Class A)", sector: "Technology" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer" },
  { symbol: "META", name: "Meta Platforms", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technology" },
  { symbol: "TSLA", name: "Tesla", sector: "Automotive" },
  { symbol: "BRK-B", name: "Berkshire Hathaway", sector: "Financials" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { symbol: "V", name: "Visa", sector: "Financials" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer" },
  { symbol: "MA", name: "Mastercard", sector: "Financials" },
  { symbol: "HD", name: "Home Depot", sector: "Consumer" },
  { symbol: "DIS", name: "Walt Disney", sector: "Communication" },
  { symbol: "NFLX", name: "Netflix", sector: "Communication" },
  { symbol: "AMD", name: "AMD", sector: "Technology" },
  { symbol: "INTC", name: "Intel", sector: "Technology" },
  { symbol: "COST", name: "Costco", sector: "Consumer" },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer" },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer" },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { symbol: "CVX", name: "Chevron", sector: "Energy" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials" },
  { symbol: "PFE", name: "Pfizer", sector: "Healthcare" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer" },
  { symbol: "NKE", name: "Nike", sector: "Consumer" },
  { symbol: "CRM", name: "Salesforce", sector: "Technology" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie", sector: "Healthcare" },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher", sector: "Healthcare" },
  { symbol: "ACN", name: "Accenture", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle", sector: "Technology" },
  { symbol: "AVGO", name: "Broadcom", sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technology" },
  { symbol: "INTU", name: "Intuit", sector: "Technology" },
  { symbol: "AMGN", name: "Amgen", sector: "Healthcare" },
  { symbol: "PYPL", name: "PayPal", sector: "Financials" },
  { symbol: "IBM", name: "IBM", sector: "Technology" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrial" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrial" },
  { symbol: "HON", name: "Honeywell", sector: "Industrial" },
  { symbol: "BA", name: "Boeing", sector: "Industrial" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "BLK", name: "BlackRock", sector: "Financials" },
  { symbol: "AXP", name: "American Express", sector: "Financials" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { symbol: "COF", name: "Capital One", sector: "Financials" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials" },
  { symbol: "C", name: "Citigroup", sector: "Financials" },
  { symbol: "MRK", name: "Merck", sector: "Healthcare" },
  { symbol: "BMY", name: "Bristol Myers Squibb", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex", sector: "Healthcare" },
  { symbol: "CVS", name: "CVS Health", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna", sector: "Healthcare" },
  { symbol: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { symbol: "HUM", name: "Humana", sector: "Healthcare" },
  { symbol: "LOW", name: "Lowe's", sector: "Consumer" },
  { symbol: "TGT", name: "Target", sector: "Consumer" },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer" },
  { symbol: "MDLZ", name: "Mondelez", sector: "Consumer" },
  { symbol: "MO", name: "Altria", sector: "Consumer" },
  { symbol: "PM", name: "Philip Morris", sector: "Consumer" },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials" },
  { symbol: "RTX", name: "RTX", sector: "Industrial" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrial" },
  { symbol: "DE", name: "Deere", sector: "Industrial" },
  { symbol: "UPS", name: "UPS", sector: "Industrial" },
  { symbol: "FDX", name: "FedEx", sector: "Industrial" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrial" },
  { symbol: "CSX", name: "CSX", sector: "Industrial" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities" },
  { symbol: "PLD", name: "Prologis", sector: "Real Estate" },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate" },
  { symbol: "EQIX", name: "Equinix", sector: "Real Estate" },
  { symbol: "ZTS", name: "Zoetis", sector: "Healthcare" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { symbol: "CB", name: "Chubb", sector: "Financials" },
  /** Yahoo chart uses MRSH; “MMC” returns 404 from Yahoo. */
  { symbol: "MRSH", name: "Marsh McLennan", sector: "Financials" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow", sector: "Technology" },
  { symbol: "MU", name: "Micron", sector: "Technology" },
  { symbol: "WDC", name: "Western Digital", sector: "Technology" },
];

export function companyBySymbol(symbol: string): Company | undefined {
  return COMPANIES.find((c) => c.symbol === symbol);
}
