/** Top 250 US large / mid-cap tickers — prices via Yahoo proxy. */
export type Company = { symbol: string; name: string; sector: string };

export const COMPANIES: Company[] = [
  { symbol: "AAPL", name: "Apple", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet (Class A)", sector: "Technology" },
  { symbol: "AMZN", name: "Amazon", sector: "Consumer" },
  { symbol: "META", name: "Meta Platforms", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Technology" },
  { symbol: "TSLA", name: "Tesla", sector: "Automotive" },
  { symbol: "BRK-B", name: "Berkshire Hathaway", sector: "Financials" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { symbol: "V", name: "Visa", sector: "Financials" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "WMT", name: "Walmart", sector: "Consumer" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer" },
  { symbol: "MA", name: "Mastercard", sector: "Financials" },
  { symbol: "HD", name: "Home Depot", sector: "Consumer" },
  { symbol: "DIS", name: "Walt Disney", sector: "Communication" },
  { symbol: "NFLX", name: "Netflix", sector: "Communication" },
  { symbol: "AMD", name: "AMD", sector: "Technology" },
  { symbol: "INTC", name: "Intel", sector: "Technology" },
  { symbol: "COST", name: "Costco", sector: "Consumer" },
  { symbol: "PEP", name: "PepsiCo", sector: "Consumer" },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer" },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { symbol: "CVX", name: "Chevron", sector: "Energy" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials" },
  { symbol: "PFE", name: "Pfizer", sector: "Healthcare" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer" },
  { symbol: "NKE", name: "Nike", sector: "Consumer" },
  { symbol: "CRM", name: "Salesforce", sector: "Technology" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie", sector: "Healthcare" },
  { symbol: "TMO", name: "Thermo Fisher", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher", sector: "Healthcare" },
  { symbol: "ACN", name: "Accenture", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle", sector: "Technology" },
  { symbol: "AVGO", name: "Broadcom", sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technology" },
  { symbol: "INTU", name: "Intuit", sector: "Technology" },
  { symbol: "AMGN", name: "Amgen", sector: "Healthcare" },
  { symbol: "PYPL", name: "PayPal", sector: "Financials" },
  { symbol: "IBM", name: "IBM", sector: "Technology" },
  { symbol: "GE", name: "GE Aerospace", sector: "Industrial" },
  { symbol: "CAT", name: "Caterpillar", sector: "Industrial" },
  { symbol: "HON", name: "Honeywell", sector: "Industrial" },
  { symbol: "BA", name: "Boeing", sector: "Industrial" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "BLK", name: "BlackRock", sector: "Financials" },
  { symbol: "AXP", name: "American Express", sector: "Financials" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { symbol: "COF", name: "Capital One", sector: "Financials" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials" },
  { symbol: "C", name: "Citigroup", sector: "Financials" },
  { symbol: "MRK", name: "Merck", sector: "Healthcare" },
  { symbol: "BMY", name: "Bristol Myers Squibb", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex", sector: "Healthcare" },
  { symbol: "CVS", name: "CVS Health", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna", sector: "Healthcare" },
  { symbol: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { symbol: "HUM", name: "Humana", sector: "Healthcare" },
  { symbol: "LOW", name: "Lowe's", sector: "Consumer" },
  { symbol: "TGT", name: "Target", sector: "Consumer" },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer" },
  { symbol: "MDLZ", name: "Mondelez", sector: "Consumer" },
  { symbol: "MO", name: "Altria", sector: "Consumer" },
  { symbol: "PM", name: "Philip Morris", sector: "Consumer" },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials" },
  { symbol: "RTX", name: "RTX", sector: "Industrial" },
  { symbol: "LMT", name: "Lockheed Martin", sector: "Industrial" },
  { symbol: "DE", name: "Deere", sector: "Industrial" },
  { symbol: "UPS", name: "UPS", sector: "Industrial" },
  { symbol: "FDX", name: "FedEx", sector: "Industrial" },
  { symbol: "UNP", name: "Union Pacific", sector: "Industrial" },
  { symbol: "CSX", name: "CSX", sector: "Industrial" },
  { symbol: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy", sector: "Utilities" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities" },
  { symbol: "PLD", name: "Prologis", sector: "Real Estate" },
  { symbol: "AMT", name: "American Tower", sector: "Real Estate" },
  { symbol: "EQIX", name: "Equinix", sector: "Real Estate" },
  { symbol: "ZTS", name: "Zoetis", sector: "Healthcare" },
  { symbol: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { symbol: "CB", name: "Chubb", sector: "Financials" },
  /** Yahoo chart uses MRSH; “MMC” returns 404 from Yahoo. */
  { symbol: "MRSH", name: "Marsh McLennan", sector: "Financials" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow", sector: "Technology" },
  { symbol: "MU", name: "Micron", sector: "Technology" },
  { symbol: "WDC", name: "Western Digital", sector: "Technology" },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Technology" },
  { symbol: "AFL", name: "Aflac", sector: "Financials" },
  { symbol: "ALL", name: "Allstate", sector: "Financials" },
  { symbol: "AIG", name: "American International Group", sector: "Financials" },
  { symbol: "ALB", name: "Albemarle", sector: "Materials" },
  { symbol: "ALLE", name: "Allegion", sector: "Industrial" },
  { symbol: "AMCR", name: "Amcor", sector: "Materials" },
  { symbol: "AME", name: "Ametek", sector: "Industrial" },
  { symbol: "AMP", name: "Ameriprise Financial", sector: "Financials" },
  { symbol: "ANSS", name: "Ansys", sector: "Technology" },
  { symbol: "AOS", name: "A. O. Smith", sector: "Industrial" },
  { symbol: "APTV", name: "Aptiv", sector: "Consumer" },
  { symbol: "ARE", name: "Alexandria Real Estate", sector: "Real Estate" },
  { symbol: "ATO", name: "Atmos Energy", sector: "Utilities" },
  { symbol: "AVB", name: "AvalonBay Communities", sector: "Real Estate" },
  { symbol: "AVY", name: "Avery Dennison", sector: "Materials" },
  { symbol: "AXON", name: "Axon Enterprise", sector: "Industrial" },
  { symbol: "BALL", name: "Ball", sector: "Materials" },
  { symbol: "BAX", name: "Baxter", sector: "Healthcare" },
  { symbol: "BXP", name: "Boston Properties", sector: "Real Estate" },
  { symbol: "CAG", name: "Conagra Brands", sector: "Consumer" },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Financials" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { symbol: "CDW", name: "CDW", sector: "Technology" },
  { symbol: "CF", name: "CF Industries", sector: "Materials" },
  { symbol: "CHD", name: "Church & Dwight", sector: "Consumer" },
  { symbol: "CHRW", name: "C.H. Robinson", sector: "Industrial" },
  { symbol: "CL", name: "Colgate-Palmolive", sector: "Consumer" },
  { symbol: "CLX", name: "Clorox", sector: "Consumer" },
  { symbol: "CMCSA", name: "Comcast", sector: "Communication" },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Utilities" },
  { symbol: "COO", name: "Cooper Companies", sector: "Healthcare" },
  { symbol: "CPB", name: "Campbell Soup", sector: "Consumer" },
  { symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate" },
  { symbol: "CRL", name: "Charles River Laboratories", sector: "Healthcare" },
  { symbol: "CTAS", name: "Cintas", sector: "Industrial" },
  { symbol: "CTSH", name: "Cognizant", sector: "Technology" },
  { symbol: "CTVA", name: "Corteva", sector: "Materials" },
  { symbol: "CZR", name: "Caesars Entertainment", sector: "Consumer" },
  { symbol: "DAL", name: "Delta Air Lines", sector: "Industrial" },
  { symbol: "DHI", name: "D.R. Horton", sector: "Consumer" },
  { symbol: "DLR", name: "Digital Realty", sector: "Real Estate" },
  { symbol: "DOV", name: "Dover", sector: "Industrial" },
  { symbol: "DRI", name: "Darden Restaurants", sector: "Consumer" },
  { symbol: "DTE", name: "DTE Energy", sector: "Utilities" },
  { symbol: "DVN", name: "Devon Energy", sector: "Energy" },
  { symbol: "DXCM", name: "Dexcom", sector: "Healthcare" },
  { symbol: "EIX", name: "Edison International", sector: "Utilities" },
  { symbol: "EL", name: "Estée Lauder", sector: "Consumer" },
  { symbol: "EMN", name: "Eastman Chemical", sector: "Materials" },
  { symbol: "ENPH", name: "Enphase Energy", sector: "Technology" },
  { symbol: "EQT", name: "EQT", sector: "Energy" },
  { symbol: "ESS", name: "Essex Property Trust", sector: "Real Estate" },
  { symbol: "ETN", name: "Eaton", sector: "Industrial" },
  { symbol: "EVRG", name: "Evergy", sector: "Utilities" },
  { symbol: "EXC", name: "Exelon", sector: "Utilities" },
  { symbol: "EXPD", name: "Expeditors International", sector: "Industrial" },
  { symbol: "EXPE", name: "Expedia Group", sector: "Consumer" },
  { symbol: "EXR", name: "Extra Space Storage", sector: "Real Estate" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { symbol: "FAST", name: "Fastenal", sector: "Industrial" },
  { symbol: "FDS", name: "FactSet", sector: "Financials" },
  { symbol: "FFIV", name: "F5", sector: "Technology" },
  { symbol: "FICO", name: "Fair Isaac", sector: "Technology" },
  { symbol: "FIS", name: "Fidelity National Information Services", sector: "Technology" },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financials" },
  { symbol: "FSLR", name: "First Solar", sector: "Technology" },
  { symbol: "FTNT", name: "Fortinet", sector: "Technology" },
  { symbol: "FTV", name: "Fortive", sector: "Industrial" },
  { symbol: "GIS", name: "General Mills", sector: "Consumer" },
  { symbol: "GL", name: "Globe Life", sector: "Financials" },
  { symbol: "GLW", name: "Corning", sector: "Technology" },
  { symbol: "GPC", name: "Genuine Parts", sector: "Consumer" },
  { symbol: "GPN", name: "Global Payments", sector: "Financials" },
  { symbol: "GRMN", name: "Garmin", sector: "Technology" },
  { symbol: "HAS", name: "Hasbro", sector: "Consumer" },
  { symbol: "HIG", name: "Hartford Financial", sector: "Financials" },
  { symbol: "HII", name: "Huntington Ingalls", sector: "Industrial" },
  { symbol: "HLT", name: "Hilton Worldwide", sector: "Consumer" },
  { symbol: "HOLX", name: "Hologic", sector: "Healthcare" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology" },
  { symbol: "HPQ", name: "HP", sector: "Technology" },
  { symbol: "HRL", name: "Hormel Foods", sector: "Consumer" },
  { symbol: "HSIC", name: "Henry Schein", sector: "Healthcare" },
  { symbol: "HST", name: "Host Hotels & Resorts", sector: "Real Estate" },
  { symbol: "HWM", name: "Howmet Aerospace", sector: "Industrial" },
  { symbol: "IDXX", name: "Idexx Laboratories", sector: "Healthcare" },
  { symbol: "IP", name: "International Paper", sector: "Materials" },
  { symbol: "IPG", name: "Interpublic Group", sector: "Communication" },
  { symbol: "IQV", name: "IQVIA", sector: "Healthcare" },
  { symbol: "IR", name: "Ingersoll Rand", sector: "Industrial" },
  { symbol: "IRM", name: "Iron Mountain", sector: "Real Estate" },
  { symbol: "IT", name: "Gartner", sector: "Technology" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrial" },
  { symbol: "IVZ", name: "Invesco", sector: "Financials" },
  { symbol: "JBHT", name: "J.B. Hunt", sector: "Industrial" },
  { symbol: "JCI", name: "Johnson Controls", sector: "Industrial" },
  { symbol: "JKHY", name: "Jack Henry & Associates", sector: "Technology" },
  { symbol: "K", name: "Kellanova", sector: "Consumer" },
  { symbol: "KEY", name: "KeyCorp", sector: "Financials" },
  { symbol: "KHC", name: "Kraft Heinz", sector: "Consumer" },
  { symbol: "KIM", name: "Kimco Realty", sector: "Real Estate" },
  { symbol: "KMB", name: "Kimberly-Clark", sector: "Consumer" },
  { symbol: "KMX", name: "CarMax", sector: "Consumer" },
  { symbol: "KR", name: "Kroger", sector: "Consumer" },
  { symbol: "L", name: "Loews", sector: "Financials" },
  { symbol: "LEN", name: "Lennar", sector: "Consumer" },
  { symbol: "LH", name: "Labcorp", sector: "Healthcare" },
  { symbol: "LHX", name: "L3Harris Technologies", sector: "Industrial" },
  { symbol: "LKQ", name: "LKQ Corporation", sector: "Consumer" },
  { symbol: "LNT", name: "Alliant Energy", sector: "Utilities" },
  { symbol: "LUV", name: "Southwest Airlines", sector: "Industrial" },
  { symbol: "LYB", name: "LyondellBasell", sector: "Materials" },
  { symbol: "MAA", name: "Mid-America Apartment", sector: "Real Estate" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer" },
  { symbol: "MAS", name: "Masco", sector: "Industrial" },
  { symbol: "MCK", name: "McKesson", sector: "Healthcare" },
  { symbol: "MET", name: "MetLife", sector: "Financials" },
  { symbol: "MGM", name: "MGM Resorts", sector: "Consumer" },
  { symbol: "MKC", name: "McCormick", sector: "Consumer" },
  { symbol: "MLM", name: "Martin Marietta", sector: "Materials" },
  { symbol: "MMM", name: "3M", sector: "Industrial" },
  { symbol: "MOH", name: "Molina Healthcare", sector: "Healthcare" },
  { symbol: "MOS", name: "Mosaic", sector: "Materials" },
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Technology" },
  { symbol: "MRNA", name: "Moderna", sector: "Healthcare" },
  { symbol: "MSI", name: "Motorola Solutions", sector: "Industrial" },
  { symbol: "MTB", name: "M&T Bank", sector: "Financials" },
  { symbol: "NCLH", name: "Norwegian Cruise Line", sector: "Consumer" },
  { symbol: "NDSN", name: "Nordson", sector: "Industrial" },
  { symbol: "NI", name: "NiSource", sector: "Utilities" },
  { symbol: "NTRS", name: "Northern Trust", sector: "Financials" },
  { symbol: "NUE", name: "Nucor", sector: "Materials" },
  { symbol: "NVR", name: "NVR", sector: "Consumer" },
  { symbol: "NWSA", name: "News Corp (Class A)", sector: "Communication" },
  { symbol: "O", name: "Realty Income", sector: "Real Estate" },
  { symbol: "ODFL", name: "Old Dominion Freight", sector: "Industrial" },
  { symbol: "ORLY", name: "O'Reilly Automotive", sector: "Consumer" },
  { symbol: "OTIS", name: "Otis Worldwide", sector: "Industrial" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { symbol: "PAYC", name: "Paycom", sector: "Technology" },
  { symbol: "PAYX", name: "Paychex", sector: "Technology" },
  { symbol: "PCAR", name: "Paccar", sector: "Industrial" },
  { symbol: "PEG", name: "Public Service Enterprise", sector: "Utilities" },
  { symbol: "PH", name: "Parker-Hannifin", sector: "Industrial" },
  { symbol: "PKG", name: "Packaging Corporation", sector: "Materials" },
  { symbol: "PNR", name: "Pentair", sector: "Industrial" },
  { symbol: "POOL", name: "Pool Corporation", sector: "Consumer" },
  { symbol: "PWR", name: "Quanta Services", sector: "Industrial" },
  { symbol: "T", name: "AT&T", sector: "Communication" },
];

export function companyBySymbol(symbol: string): Company | undefined {
  return COMPANIES.find((c) => c.symbol === symbol);
}
